version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_passwort_1234!
      MYSQL_USER: admin
      MYSQL_PASSWORD: password1234!ABC
      MYSQL_DATABASE: customerDB
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    command: [ "--init-file", "/docker-entrypoint-initdb.d/schema.sql" ]
    container_name: my-mysql-container

volumes:
  db-data: {}